.\" This is a comment
.\" Contact Chuck Lane lane@duphy4.physics.drexel.edu
.TH Take2024Waveforms 1  "USBTMC DAQ"
.SH NAME
Take2024Waveforms \- fetch waveform data from TDS2024B oscilloscope
.SH SYNOPSIS
.B Take2024Waveforms
[OPTION]... [>output]

.SH DESCRIPTION
This program was written for the Tektronix 2024B oscilloscope
with a USBTMC connection. It might work for other, similar
oscilloscopes, but maybe not. 
.PP
The device is (optionally) selected by manufacturer, product name,
and serial number, defaulting to a Tektronix TDS2024B. These
options use  simple shell-style 'glob' wildcards, so 'Tek*' will
match 'Tektronix'. 
.PP
The oscilloscope configuration is fetched, and stored as part of the
output data file (see DATA FORMAT).
.PP
.B Normal Triggering:
in this case, the trigger conditions are set on the oscilloscope (which channel, slope, level, etc), and the waveforms are fetched when a scope trigger is detected.
.PP
.B Self Triggering:
in this case, the oscilloscope trigger is disabled, and the program is used to initiate triggering, sending a
.B *TRG
command after a fixed delay. This is mostly of use to get a random snapshot of
waveform data.
.PP
This program can be gracefully terminated with a Control-C, or by issuing
a 'kill' command.  

.SH OPTIONS
.TP
.B -h     --help
show short usage message
.TP
.B -q     --quiet
no informative chatter output
.TP
.B -d     --debug
increment debug output level
.TP
.BI  "-o" "file" "    --out=" "file"
output file, if not supplied, output goes to STDOUT
.TP
.BI "-f" ""      "    --force"
force overwritting of existing output file
.TP
.BI "-s" "DEL"   "    --self=" "DEL"
force triggers from software, delay DEL between triggers
.TP
.BI "-n" "N"     "    --nevents=" "N"
number of events to read, N=0 means infinite (default)
.TP
.BI "-i" "STR"   "    --id=" "STR"
includes an STR in the output file, to
help document the acquisition conditions.
.TP
.BI "-c" "CLIST" "    --channels=" "CLIST"
Channels to be read. CLIST is a comma-separated
list, taken from: CH1,CH2,CH3,CH4,REF1,REF2,REF3,REF4,MATH.
Default: whatever channels are being displayed. 
Note: channels that the scope considers 'off' are not read.
.TP
.BI "-m" "MFR" "    --manufacter=" "MFR"
manufacturer name
.I MFR
(Default: 'Tek*')
.TP
.BI "-p" "PROD" "    --product=" "PROD"
device product name
.I PROD
(Default: 'TDS*2024*')
.TP
.BI "-s" "SN" "    --serial=" "SN"
device serial number
.I SN
(Default: '*')
.SH DATA FORMAT
The output file has a very simple somewhat readable format, just recording the
conversation between the scope and the program.  Each line of the file is prefixed with a character to indicate the direction of data flow:
.PP
.B ">"
data sent TO the scope, from the software. As a special case, comments are
placed in the data file using a prefix
.B ">REM "
which is followed by such things as the "ID", start and stop times, event numbers, etc. 
.PP
.B "<"
data read FROM the scope.
.PP
At the beginning of the data, the scope configuration is stored by sending a
'SET?' command. The scope aquisition state is also fetched, and restored at the end of the program. 
.PP
The waveform data files produced by this program can be analyzed using the Perl TDS2024B module, and associated applications. 

.SH SEE ALSO
TMC(3pm), Set2024Config(1), Get2024Config(1), ScreenCap2024(1), TDS2024B(3pm)
.SH BUGS
Copious, yet undiscovered. 
.SH AUTHOR
Chuck Lane (lane@duphy4.physics.drexel.edu)
